### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-packer.git`](https://github.com/cisagov/skeleton-packer.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

## ✅ Pre-approval checklist ##

Remove any of the following that do not apply. If you're unsure about any of these, don't hesitate to ask. We're here to help!

- [x] All relevant type-of-change labels have been added.
- [x] All new and existing tests pass.

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]

**Comment by jsf9k** [comment]
This is happening even though cisagov/ansible-role-openvpn#70 passed all its automated tests.  The difference is due to [this line](https://github.com/geerlingguy/docker-debian11-ansible/blob/master/Dockerfile#L19-L20) in the `Dockerfile` of @geerlingguy's SystemD-enabled Debian Bullseye Docker image.  This installs a newer version of `pip` than is available from the system package manager, and that newer version is aware of the `--break-system-packages` CLI option whereas the latest version via the package manager is not.

I will address the issue in [cisagov/ansible-role-openvpn](https://github.com/cisagov/ansible-role-openvpn) for now.  Moving forward, we have two options:
- Attempt to convince @geerlingguy that installing Python packages against the system `python` via `pip` vice the system package manager is a bad idea.  (FWIW, this philosophy is [soon to be enforced via `pip` itself](https://github.com/pypa/pip/pull/11780).)
- Generate our own SystemD-enabled Docker images that _do not_ install Python packages against the system Python via `pip`.

**Comment by jsf9k** [comment]
> I will address the issue in [cisagov/ansible-role-openvpn](https://github.com/cisagov/ansible-role-openvpn) for now.

Well this is awkward.  The version of `pip` available in the `python3-pip` system package for Debian Bullseye, Bookworm, and Kali _does not_ support the `--break-system-packages` CLI option.  So the SystemD-enabled Docker images we use for Molecule testing do not faithfully represent what we see when installing against those systems.  We can either pass Molecule tests or successfully install on an actual system, but not both.  Not good.

**Comment by mcdonnnj** [comment]
> 

Bookworm should support the flag per https://packages.debian.org/bookworm/python3-pip and https://pip.pypa.io/en/stable/news/#v23-0-1, but none of the other Debian versions do. However it is not until Debian Bookworm that the Python environment is marked as externally managed no? I think if we adjust https://github.com/cisagov/ansible-role-openvpn/blob/d694c3bec6446b6f03df73d6ff913768b54efe11/tasks/install_verify_cn.yml#L15 to only offer the option for Debian Bookworm it should be ok. Also I will adjust [cisagov/docker-debian12-ansible](https://github.com/cisagov/docker-debian12-ansible) to no longer upgrade the `pip` package.

**Edit**: Kali should also support the flag per https://www.kali.org/tools/python-pip/

**Comment by jsf9k** [comment]
> > 
> 
> Bookworm should support the flag per https://packages.debian.org/bookworm/python3-pip and https://pip.pypa.io/en/stable/news/#v23-0-1, but none of the other Debian versions do. However it is not until Debian Bookworm that the Python environment is marked as externally managed no? I think if we adjust https://github.com/cisagov/ansible-role-openvpn/blob/d694c3bec6446b6f03df73d6ff913768b54efe11/tasks/install_verify_cn.yml#L15 to only offer the option for Debian Bookworm it should be ok. Also I will adjust [cisagov/docker-debian12-ansible](https://github.com/cisagov/docker-debian12-ansible) to no longer upgrade the `pip` package.
> 
> **Edit**: Kali should also support the flag per https://www.kali.org/tools/python-pip/

Hmmm...I tested installing `python3-pip` into Bullseye, Bookworm, and Kali and in all three cases `pip` didn't seem to recognize the option.  I'm curious what I did wrong.

**Comment by jsf9k** [comment]
> Hmmm...I tested installing `python3-pip` into Bullseye, Bookworm, and Kali and in all three cases `pip` didn't seem to recognize the option. I'm curious what I did wrong.

Ah, I tested via `pip3 --break-system-packages` instead of something like `pip3 install --break-system-packages semver`.  Rookie mistake.

**Review by dav3r — APPROVED** [review]

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Review by dav3r — APPROVED** [review]

**Pull request merged**
