### PR TITLE
Add Tanium client and Nessus Agent for the CISA CDM environment

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request adds the Tanium client and the Nessus Agent for the CISA CDM environment.  It also configures UFW to allow the required traffic for the CISA CDM environment.

## 💭 Motivation and context ##

Our Shared Services instances must be scannable from the CISA CDM environment.

## 🧪 Testing ##

I successfully built and deployed a new AMI for our COOL staging environment and verified that it functioned as expected.

## ✅ Pre-approval checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.
* [x] Build a staging AMI
* [x] Deploy staging AMI
* [x] Test staging AMI
* [x] Revert to the `develop` branch of [cisagov/ansible-role-cdm-tanium-client](https://github.com/cisagov/ansible-role-cdm-tanium-client)
* [x] Revert to the `develop` branch of [cisagov/ansible-role-cdm-nessus-agent](https://github.com/cisagov/ansible-role-cdm-nessus-agent)

## ✅ Pre-merge checklist ##
* [x] Finalize version
* [x] Build a production AMI

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Where have I seen all of this before... 👍 👍

**Review by hillaryj — APPROVED** [review]
🌮

**Review by dav3r — APPROVED** [review]
👍 👍 👍

**Review by hillaryj — APPROVED** [review]
🎩

**Pull request merged**
