### PR TITLE
Bump version to freshen AMIs

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This PR bumps the version on this repository in order to freshen up the AMI.

## 💭 Motivation and Context

We want to pick up any security patches issued by the Linux distribution.  We also need fresh images for security and compliance scanning.

## 🧪 Testing

I build new images for production and staging and successfully deployed them to the appropriate environments.

## 🚥 Types of Changes

- Version bump

## ✅ Checklist

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.
- [x] New AMI successfully deployed to staging
- [x] New AMI successfully deployed to production

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
🧙‍♂️

**Review by mcdonnnj — APPROVED** [review]
✨

**Comment by jsf9k** [comment]
I need a review from @felddy before I can merge this PR.

**Review by hillaryj — APPROVED** [review]
🎉

**Review by felddy — APPROVED** [review]
A treasure to be sure! 🏴‍☠️

**Pull request merged**
