### PR TITLE
Hardening role must not obliterate ssh banner

### LINKED ISSUE #98: Move Banner role after Harden role
# 🐛 Summary #

The banner role sets the custom CISA banners to `/etc/motd`, `/etc/issue`, and `/etc/issue.net`. However, the harden role reverts them to default generic CIS Benchmarks settings. The task for running the banner role should be moved from `base.yml` to the end of `harden.yml`

## To reproduce ##

1. Build AMI
2. Banner is set to default CIS Benchmarks generic banner

## Expected behavior ##

Banner should be CISA custom banner

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request modifies the `harden.yml` Ansible playbook to:
1. Download the `issue` and `motd` files from [cisagov/ansible-role-banner](https://github.com/cisagov/ansible-role-banner).
2. Modify the configuration of [cisagov/ansible-role-hardening-2](https://github.com/cisagov/ansible-role-hardening-2) to use the downloaded files when setting the `sshd` banner.

## 💭 Motivation and context ##

Resolves #98.

## 🧪 Testing ##

All automated tests pass.  I also created and tested a new OpenVPN AMI with these changes for our COOL staging environment and found that it functions as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Build and test a staging AMI with these changes.
- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
LGTM 👍 

Can `/tmp/issue` and `/tmp/motd` be safely deleted after the hardening role has run?

**Review by dv4harr10 — APPROVED** [review]

**Comment by jsf9k** [comment]
> LGTM 👍
> 
> Can `/tmp/issue` and `/tmp/motd` be safely deleted after the hardening role has run?

Yes, but they are non-sensitive files saved to the Ansible controller's `/tmp` directory so I didn't bother.  If you really want me to then I can delete them.

**Comment by dav3r** [comment]
> > LGTM 👍
> > Can `/tmp/issue` and `/tmp/motd` be safely deleted after the hardening role has run?
> 
> Yes, but they are non-sensitive files saved to the Ansible controller's `/tmp` directory so I didn't bother. If you really want me to then I can delete them.

It's not a huge deal, but we are usually good about cleaning up temp files after we are done with them.  If it isn't too much work, I say we should do that here as well.

**Comment by jsf9k** [comment]
> > > LGTM 👍
> > > Can `/tmp/issue` and `/tmp/motd` be safely deleted after the hardening role has run?
> > 
> > 
> > Yes, but they are non-sensitive files saved to the Ansible controller's `/tmp` directory so I didn't bother. If you really want me to then I can delete them.
> 
> It's not a huge deal, but we are usually good about cleaning up temp files after we are done with them. If it isn't too much work, I say we should do that here as well.

Please enjoy commit bf004a1.

**Review by dav3r — APPROVED** [review]
👍 👍

**Pull request merged**
