### PR TITLE
Bump version for monthly rebuild

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request bumps the version for the monthly AMI rebuild.

## 💭 Motivation and Context ##

We want to rebuild the AMIs used in the Shared Services account on a monthly cadence.

## 🧪 Testing ##

Not yet...but I will successfully deploy these changes to our production COOL environment.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Impressive! 🥧

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Review by felddy — APPROVED** [review]
This looks good even with one eye! 👁

**Review by hillaryj — APPROVED** [review]
👍🏻

**Pull request merged**
